// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.opengis.nix;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.opengis.nix.DispositivoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DispositivoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DispositivoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DispositivoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DispositivoIntegrationTest: @Transactional;
    
    @Autowired
    private DispositivoDataOnDemand DispositivoIntegrationTest.dod;
    
    @Test
    public void DispositivoIntegrationTest.testCountDispositivoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to initialize correctly", dod.getRandomDispositivo());
        long count = org.opengis.nix.Dispositivo.countDispositivoes();
        org.junit.Assert.assertTrue("Counter for 'Dispositivo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DispositivoIntegrationTest.testFindDispositivo() {
        org.opengis.nix.Dispositivo obj = dod.getRandomDispositivo();
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to provide an identifier", id);
        obj = org.opengis.nix.Dispositivo.findDispositivo(id);
        org.junit.Assert.assertNotNull("Find method for 'Dispositivo' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Dispositivo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DispositivoIntegrationTest.testFindAllDispositivoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to initialize correctly", dod.getRandomDispositivo());
        long count = org.opengis.nix.Dispositivo.countDispositivoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Dispositivo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.opengis.nix.Dispositivo> result = org.opengis.nix.Dispositivo.findAllDispositivoes();
        org.junit.Assert.assertNotNull("Find all method for 'Dispositivo' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Dispositivo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DispositivoIntegrationTest.testFindDispositivoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to initialize correctly", dod.getRandomDispositivo());
        long count = org.opengis.nix.Dispositivo.countDispositivoes();
        if (count > 20) count = 20;
        java.util.List<org.opengis.nix.Dispositivo> result = org.opengis.nix.Dispositivo.findDispositivoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Dispositivo' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Dispositivo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DispositivoIntegrationTest.testFlush() {
        org.opengis.nix.Dispositivo obj = dod.getRandomDispositivo();
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to provide an identifier", id);
        obj = org.opengis.nix.Dispositivo.findDispositivo(id);
        org.junit.Assert.assertNotNull("Find method for 'Dispositivo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDispositivo(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Dispositivo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DispositivoIntegrationTest.testMerge() {
        org.opengis.nix.Dispositivo obj = dod.getRandomDispositivo();
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to provide an identifier", id);
        obj = org.opengis.nix.Dispositivo.findDispositivo(id);
        boolean modified =  dod.modifyDispositivo(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.opengis.nix.Dispositivo merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Dispositivo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DispositivoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to initialize correctly", dod.getRandomDispositivo());
        org.opengis.nix.Dispositivo obj = dod.getNewTransientDispositivo(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Dispositivo' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Dispositivo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DispositivoIntegrationTest.testRemove() {
        org.opengis.nix.Dispositivo obj = dod.getRandomDispositivo();
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dispositivo' failed to provide an identifier", id);
        obj = org.opengis.nix.Dispositivo.findDispositivo(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Dispositivo' with identifier '" + id + "'", org.opengis.nix.Dispositivo.findDispositivo(id));
    }
    
}
