// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.opengis.nix;

import java.lang.Boolean;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.opengis.nix.Dispositivo;
import org.springframework.stereotype.Component;

privileged aspect DispositivoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DispositivoDataOnDemand: @Component;
    
    private Random DispositivoDataOnDemand.rnd = new SecureRandom();
    
    private List<Dispositivo> DispositivoDataOnDemand.data;
    
    public Dispositivo DispositivoDataOnDemand.getNewTransientDispositivo(int index) {
        Dispositivo obj = new Dispositivo();
        setActivo(obj, index);
        setDisponible(obj, index);
        setModelo(obj, index);
        setNumSerie(obj, index);
        return obj;
    }
    
    public void DispositivoDataOnDemand.setActivo(Dispositivo obj, int index) {
        Boolean activo = Boolean.TRUE;
        obj.setActivo(activo);
    }
    
    public void DispositivoDataOnDemand.setDisponible(Dispositivo obj, int index) {
        Boolean disponible = Boolean.TRUE;
        obj.setDisponible(disponible);
    }
    
    public void DispositivoDataOnDemand.setModelo(Dispositivo obj, int index) {
        String modelo = "modelo_" + index;
        if (modelo.length() > 20) {
            modelo = modelo.substring(0, 20);
        }
        obj.setModelo(modelo);
    }
    
    public void DispositivoDataOnDemand.setNumSerie(Dispositivo obj, int index) {
        String numSerie = "numSerie_" + index;
        if (numSerie.length() > 20) {
            numSerie = numSerie.substring(0, 20);
        }
        obj.setNumSerie(numSerie);
    }
    
    public Dispositivo DispositivoDataOnDemand.getSpecificDispositivo(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Dispositivo obj = data.get(index);
        return Dispositivo.findDispositivo(obj.getId());
    }
    
    public Dispositivo DispositivoDataOnDemand.getRandomDispositivo() {
        init();
        Dispositivo obj = data.get(rnd.nextInt(data.size()));
        return Dispositivo.findDispositivo(obj.getId());
    }
    
    public boolean DispositivoDataOnDemand.modifyDispositivo(Dispositivo obj) {
        return false;
    }
    
    public void DispositivoDataOnDemand.init() {
        data = Dispositivo.findDispositivoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Dispositivo' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.opengis.nix.Dispositivo>();
        for (int i = 0; i < 10; i++) {
            Dispositivo obj = getNewTransientDispositivo(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
