// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.opengis.nix;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.opengis.nix.PrestamoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrestamoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrestamoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrestamoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PrestamoIntegrationTest: @Transactional;
    
    @Autowired
    private PrestamoDataOnDemand PrestamoIntegrationTest.dod;
    
    @Test
    public void PrestamoIntegrationTest.testCountPrestamoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to initialize correctly", dod.getRandomPrestamo());
        long count = org.opengis.nix.Prestamo.countPrestamoes();
        org.junit.Assert.assertTrue("Counter for 'Prestamo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrestamoIntegrationTest.testFindPrestamo() {
        org.opengis.nix.Prestamo obj = dod.getRandomPrestamo();
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to provide an identifier", id);
        obj = org.opengis.nix.Prestamo.findPrestamo(id);
        org.junit.Assert.assertNotNull("Find method for 'Prestamo' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Prestamo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PrestamoIntegrationTest.testFindAllPrestamoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to initialize correctly", dod.getRandomPrestamo());
        long count = org.opengis.nix.Prestamo.countPrestamoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Prestamo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.opengis.nix.Prestamo> result = org.opengis.nix.Prestamo.findAllPrestamoes();
        org.junit.Assert.assertNotNull("Find all method for 'Prestamo' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Prestamo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PrestamoIntegrationTest.testFindPrestamoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to initialize correctly", dod.getRandomPrestamo());
        long count = org.opengis.nix.Prestamo.countPrestamoes();
        if (count > 20) count = 20;
        java.util.List<org.opengis.nix.Prestamo> result = org.opengis.nix.Prestamo.findPrestamoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Prestamo' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Prestamo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrestamoIntegrationTest.testFlush() {
        org.opengis.nix.Prestamo obj = dod.getRandomPrestamo();
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to provide an identifier", id);
        obj = org.opengis.nix.Prestamo.findPrestamo(id);
        org.junit.Assert.assertNotNull("Find method for 'Prestamo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPrestamo(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Prestamo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrestamoIntegrationTest.testMerge() {
        org.opengis.nix.Prestamo obj = dod.getRandomPrestamo();
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to provide an identifier", id);
        obj = org.opengis.nix.Prestamo.findPrestamo(id);
        boolean modified =  dod.modifyPrestamo(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.opengis.nix.Prestamo merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Prestamo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PrestamoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to initialize correctly", dod.getRandomPrestamo());
        org.opengis.nix.Prestamo obj = dod.getNewTransientPrestamo(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Prestamo' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Prestamo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PrestamoIntegrationTest.testRemove() {
        org.opengis.nix.Prestamo obj = dod.getRandomPrestamo();
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Prestamo' failed to provide an identifier", id);
        obj = org.opengis.nix.Prestamo.findPrestamo(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Prestamo' with identifier '" + id + "'", org.opengis.nix.Prestamo.findPrestamo(id));
    }
    
}
