// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.opengis.nix;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.opengis.nix.ProductoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProductoIntegrationTest: @Transactional;
    
    @Autowired
    private ProductoDataOnDemand ProductoIntegrationTest.dod;
    
    @Test
    public void ProductoIntegrationTest.testCountProductoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", dod.getRandomProducto());
        long count = org.opengis.nix.Producto.countProductoes();
        org.junit.Assert.assertTrue("Counter for 'Producto' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductoIntegrationTest.testFindProducto() {
        org.opengis.nix.Producto obj = dod.getRandomProducto();
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to provide an identifier", id);
        obj = org.opengis.nix.Producto.findProducto(id);
        org.junit.Assert.assertNotNull("Find method for 'Producto' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Producto' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductoIntegrationTest.testFindAllProductoes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", dod.getRandomProducto());
        long count = org.opengis.nix.Producto.countProductoes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Producto', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.opengis.nix.Producto> result = org.opengis.nix.Producto.findAllProductoes();
        org.junit.Assert.assertNotNull("Find all method for 'Producto' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Producto' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductoIntegrationTest.testFindProductoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", dod.getRandomProducto());
        long count = org.opengis.nix.Producto.countProductoes();
        if (count > 20) count = 20;
        java.util.List<org.opengis.nix.Producto> result = org.opengis.nix.Producto.findProductoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Producto' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Producto' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductoIntegrationTest.testFlush() {
        org.opengis.nix.Producto obj = dod.getRandomProducto();
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to provide an identifier", id);
        obj = org.opengis.nix.Producto.findProducto(id);
        org.junit.Assert.assertNotNull("Find method for 'Producto' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProducto(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Producto' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductoIntegrationTest.testMerge() {
        org.opengis.nix.Producto obj = dod.getRandomProducto();
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to provide an identifier", id);
        obj = org.opengis.nix.Producto.findProducto(id);
        boolean modified =  dod.modifyProducto(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.opengis.nix.Producto merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Producto' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", dod.getRandomProducto());
        org.opengis.nix.Producto obj = dod.getNewTransientProducto(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Producto' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Producto' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductoIntegrationTest.testRemove() {
        org.opengis.nix.Producto obj = dod.getRandomProducto();
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Producto' failed to provide an identifier", id);
        obj = org.opengis.nix.Producto.findProducto(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Producto' with identifier '" + id + "'", org.opengis.nix.Producto.findProducto(id));
    }
    
}
