// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.opengis.nix;

import java.lang.Boolean;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.opengis.nix.Usuario;
import org.opengis.nix.enumerated.TipoUser;
import org.springframework.stereotype.Component;

privileged aspect UsuarioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsuarioDataOnDemand: @Component;
    
    private Random UsuarioDataOnDemand.rnd = new SecureRandom();
    
    private List<Usuario> UsuarioDataOnDemand.data;
    
    public Usuario UsuarioDataOnDemand.getNewTransientUsuario(int index) {
        Usuario obj = new Usuario();
        setActivo(obj, index);
        setApellidos(obj, index);
        setCodPostal(obj, index);
        setDireccion(obj, index);
        setDni(obj, index);
        setFechaNacimiento(obj, index);
        setNombre(obj, index);
        setPoblacion(obj, index);
        setProvincia(obj, index);
        setTelefono(obj, index);
        setTipo(obj, index);
        return obj;
    }
    
    public void UsuarioDataOnDemand.setActivo(Usuario obj, int index) {
        Boolean activo = Boolean.TRUE;
        obj.setActivo(activo);
    }
    
    public void UsuarioDataOnDemand.setApellidos(Usuario obj, int index) {
        String apellidos = "apellidos_" + index;
        if (apellidos.length() > 30) {
            apellidos = apellidos.substring(0, 30);
        }
        obj.setApellidos(apellidos);
    }
    
    public void UsuarioDataOnDemand.setCodPostal(Usuario obj, int index) {
        String codPostal = "codPostal_" + index;
        obj.setCodPostal(codPostal);
    }
    
    public void UsuarioDataOnDemand.setDireccion(Usuario obj, int index) {
        String direccion = "direccion_" + index;
        if (direccion.length() > 40) {
            direccion = direccion.substring(0, 40);
        }
        obj.setDireccion(direccion);
    }
    
    public void UsuarioDataOnDemand.setDni(Usuario obj, int index) {
        String dni = "dni_" + index;
        obj.setDni(dni);
    }
    
    public void UsuarioDataOnDemand.setFechaNacimiento(Usuario obj, int index) {
        Date fechaNacimiento = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaNacimiento(fechaNacimiento);
    }
    
    public void UsuarioDataOnDemand.setNombre(Usuario obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 30) {
            nombre = nombre.substring(0, 30);
        }
        obj.setNombre(nombre);
    }
    
    public void UsuarioDataOnDemand.setPoblacion(Usuario obj, int index) {
        String poblacion = "poblacion_" + index;
        if (poblacion.length() > 20) {
            poblacion = poblacion.substring(0, 20);
        }
        obj.setPoblacion(poblacion);
    }
    
    public void UsuarioDataOnDemand.setProvincia(Usuario obj, int index) {
        String provincia = "provincia_" + index;
        if (provincia.length() > 20) {
            provincia = provincia.substring(0, 20);
        }
        obj.setProvincia(provincia);
    }
    
    public void UsuarioDataOnDemand.setTelefono(Usuario obj, int index) {
        String telefono = "telefono_" + index;
        obj.setTelefono(telefono);
    }
    
    public void UsuarioDataOnDemand.setTipo(Usuario obj, int index) {
        TipoUser tipo = TipoUser.class.getEnumConstants()[0];
        obj.setTipo(tipo);
    }
    
    public Usuario UsuarioDataOnDemand.getSpecificUsuario(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Usuario obj = data.get(index);
        return Usuario.findUsuario(obj.getId());
    }
    
    public Usuario UsuarioDataOnDemand.getRandomUsuario() {
        init();
        Usuario obj = data.get(rnd.nextInt(data.size()));
        return Usuario.findUsuario(obj.getId());
    }
    
    public boolean UsuarioDataOnDemand.modifyUsuario(Usuario obj) {
        return false;
    }
    
    public void UsuarioDataOnDemand.init() {
        data = Usuario.findUsuarioEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Usuario' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.opengis.nix.Usuario>();
        for (int i = 0; i < 10; i++) {
            Usuario obj = getNewTransientUsuario(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
