// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.opengis.nix;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Dispositivo_Roo_Configurable {
    
    declare @type: Dispositivo: @Configurable;
    
}
