// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ogg;

import ogg.UsuariosDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsuariosIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsuariosIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsuariosIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: UsuariosIntegrationTest: @Transactional;
    
    @Autowired
    private UsuariosDataOnDemand UsuariosIntegrationTest.dod;
    
    @Test
    public void UsuariosIntegrationTest.testCountUsuarioses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to initialize correctly", dod.getRandomUsuarios());
        long count = ogg.Usuarios.countUsuarioses();
        org.junit.Assert.assertTrue("Counter for 'Usuarios' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsuariosIntegrationTest.testFindUsuarios() {
        ogg.Usuarios obj = dod.getRandomUsuarios();
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to provide an identifier", id);
        obj = ogg.Usuarios.findUsuarios(id);
        org.junit.Assert.assertNotNull("Find method for 'Usuarios' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Usuarios' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsuariosIntegrationTest.testFindAllUsuarioses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to initialize correctly", dod.getRandomUsuarios());
        long count = ogg.Usuarios.countUsuarioses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Usuarios', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<ogg.Usuarios> result = ogg.Usuarios.findAllUsuarioses();
        org.junit.Assert.assertNotNull("Find all method for 'Usuarios' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Usuarios' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsuariosIntegrationTest.testFindUsuariosEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to initialize correctly", dod.getRandomUsuarios());
        long count = ogg.Usuarios.countUsuarioses();
        if (count > 20) count = 20;
        java.util.List<ogg.Usuarios> result = ogg.Usuarios.findUsuariosEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Usuarios' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Usuarios' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsuariosIntegrationTest.testFlush() {
        ogg.Usuarios obj = dod.getRandomUsuarios();
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to provide an identifier", id);
        obj = ogg.Usuarios.findUsuarios(id);
        org.junit.Assert.assertNotNull("Find method for 'Usuarios' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsuarios(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Usuarios' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsuariosIntegrationTest.testMerge() {
        ogg.Usuarios obj = dod.getRandomUsuarios();
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to provide an identifier", id);
        obj = ogg.Usuarios.findUsuarios(id);
        boolean modified =  dod.modifyUsuarios(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        ogg.Usuarios merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Usuarios' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsuariosIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to initialize correctly", dod.getRandomUsuarios());
        ogg.Usuarios obj = dod.getNewTransientUsuarios(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Usuarios' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Usuarios' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsuariosIntegrationTest.testRemove() {
        ogg.Usuarios obj = dod.getRandomUsuarios();
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Usuarios' failed to provide an identifier", id);
        obj = ogg.Usuarios.findUsuarios(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Usuarios' with identifier '" + id + "'", ogg.Usuarios.findUsuarios(id));
    }
    
}
